[package]
name = "LongSymbols"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Tom Folgmann"]
license = "GPL-3.0"
description = "Stretch symbols to match customizable lengths. Hotfix for missing native support for long arrows in Typst."